Created the endpoint that gives all the details about a recipe
EndavaCollab/bvdapprenticeship2024-recipe-box pull request #14
Opened 2024-08-23 06:53 UTC by Ionel14

2024-08-23 09:44 UTC, SocaciVictor commented on recipe-box-backend/src/main/java/com/endava/recipebox/controller/RecipeController.java
> +        if (recipe.getRecipeStatus().equals(RecipeStatus.PRIVATE) && !Objects.equals(recipe.getUser().getId(), userId)) {
Nu puteai sa pui direct " !recipe.getUser().getId().equals(userId) ", daca tot l ai verificat mai sus sa nu fie null ?

2024-08-23 12:33 UTC, Ionel14 commented on recipe-box-backend/src/main/java/com/endava/recipebox/controller/RecipeController.java
> +        if (recipe.getRecipeStatus().equals(RecipeStatus.PRIVATE) && !Objects.equals(recipe.getUser().getId(), userId)) {
Corect, asa o sa fac. Mersi!

2024-08-27 14:05 UTC, en-madalina-marales requested changes

2024-08-27 14:05 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/controller/RecipeController.java
> +    public ResponseEntity<?> getRecipeById(@RequestParam Long recipeId, @RequestParam Long userId) {
Generic wildcard types should not be used in return types, Replace with specific type returned.
Also check again the requirements from task. There are specified multiple fields to be returned, and I can see that in RecipeDTO there were deleted a lot of fields, that must be present in the response body

2024-08-27 14:05 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/controller/RecipeController.java
> +    @GetMapping("/details")
Please read the naming convention: https://medium.com/@nadinCodeHat/rest-api-naming-conventions-and-best-practices-1c4e781eb6a5. The endpoint is not respecting the requirements from task:
- If the user is not logged in, return the basic recipe details based on the recipeId.
- If the user is logged in, use both the recipeId and userId to return more detailed or personalized recipe information.
So, in the end the endpoint uri will look like: /recipes/{id}?userId={userId}. Please change accordingly

2024-08-27 14:05 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/controller/RecipeController.java
> +        if (recipeId == null || userId == null)
not both of the values as mandatory. Please refactor the method body, to handle:
- check presence of recipe id, if yes proceed with checking if the user id is provided, and if yes, search for recipe by userId and recipeId, otherwise(if only the recipe is provided, search for recipe by id in database)
So in the end you will need to call 2 methods from service level

2024-08-27 14:05 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/controller/RecipeController.java
> +        return ResponseEntity.ok(recipe);
Recipe object is used only for persistence layer.
Use a DTO object for response, and not directly the Recipe class

2024-08-27 14:05 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/service/impl/RecipeServiceImpl.java
> +        return recipeRepository.findById(recipeId);
is missing the mapping part

2024-08-27 14:05 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/service/impl/RecipeServiceImpl.java
> +        return recipeRepository.findById(recipeId);
you need another method to search for recipe id and user id in database

2024-08-29 08:17 UTC, en-madalina-marales approved these changes

2024-08-29 08:30 UTC, merged