GET private recipes
EndavaCollab/bvdapprenticeship2024-recipe-box pull request #20
Opened 2024-08-29 21:48 UTC by BNechita11

I created an endpoint that was supposed to retrieve a list of the user’s private recipes.

2024-08-30 10:15 UTC, en-madalina-marales requested changes

2024-08-30 10:15 UTC, en-madalina-marales commented on recipe-box-backend/src/main/java/com/endava/recipebox/service/impl/RecipeServiceImpl.java
> +        return recipeMapper.map(recipeRepository.findAll().stream()
What will be the behavior in case there is no recipe found for userId?

2024-09-09 08:22 UTC, en-alexandra-costache approved these changes

2024-09-10 05:51 UTC, en-madalina-marales approved these changes

2024-09-10 05:53 UTC, en-madalina-marales approved these changes

2024-09-11 12:43 UTC, merged