created page structure(header&&footer)
EndavaCollab/bvdapprenticeship2024-recipe-box pull request #9
Opened 2024-08-15 22:52 UTC by BNechita11

In cazul tichetului meu, poza pentru cum ar trebui sa arate header-ul era unavailable, dar m-am uitat pe alte tichete si am reusit s-o fac sa arate cat de cat la fel(sper).

2024-08-16 09:39 UTC, AlinFlorescu80 reviewed
Am vazut ca Marius e foarte atent la detalii, deci am incercat sa fac la fel, I'm so sorry :)))

2024-08-16 09:39 UTC, AlinFlorescu80 commented on recipe-box-frontend/src/main/frontend/src/components/Footer.css
> +}
Ca sa faci incadrarea circulara, ai putea incerca un `line-height: normal;`. (Ajuta putin si sa pui `padding: 0.25em 0.4em;`). Also, nu avem nevoie de `text-align: center;`

2024-08-16 09:39 UTC, AlinFlorescu80 commented on recipe-box-frontend/src/main/frontend/src/components/Header.js
> +                                Recipes <span className={`arrow ${dropdownOpen ? 'open' : ''}`}>▼</span>
Foarte faina animatia, tho caracterul de care era nevoie cred ca e "chevron down", o sa ti-l las aici sa-i poti da copy-paste: ⌵. Also, ar trebui sa bolduiesti i think

2024-08-16 09:39 UTC, AlinFlorescu80 commented on recipe-box-frontend/src/main/frontend/src/components/Header.js
> +                            <Link to="/addnewrecipe" className="button">Add New Recipe</Link>
All caps aici

2024-08-16 10:14 UTC, AlinFlorescu80 commented on recipe-box-frontend/src/main/frontend/src/components/Header.css
> +}
Am uitat sa dau add la comentariul asta: Spatiul liber din stanga trebuie sa fie egal cu spatiul liber din dreapta, care e de 80px (am masurat cu Shottr), deci, ar ajuta aici un `margin-right: 75px;`

2024-08-20 06:31 UTC, en-marius-gociman requested changes
Fișierele de tip `.js` vor trebui toate redenumite cu extensia `.tsx`, având în vedere că folosim typescript. Indicat ar fi să avem și câte un folder pentru fiecare componentă

2024-08-20 06:31 UTC, en-marius-gociman commented on recipe-box-frontend/src/main/frontend/src/components/Footer.js
> +            <p><span className="copy-symbol">&copy;</span> 2021 <span className="bold-small">ENDAVA</span></p>
Aici poți folosi anul curent, plus grijă la formatarea componentei

2024-08-20 06:31 UTC, en-marius-gociman commented on recipe-box-frontend/src/main/frontend/src/components/Header.js
> +                                Recipes <span className={`arrow ${dropdownOpen ? 'open' : ''} arrow`}>⌵</span>
Aici ar fi mers să alternezi între 2 caractere, nu neapărat între 2 clase de CSS, just fyi

2024-08-20 06:31 UTC, en-marius-gociman commented on recipe-box-frontend/src/main/frontend/src/components/Header.js
> +                        <li className="dropdown">
Cred că în varianta asta a aplicației putem să nu avem lista de elemente de navigare, sorry dacă a fost ceva neînregulă ticketul. Bara de navigare va fi utilă pentru userii care se vor putea loga în aplicație (cook, admin) pentru a-și putea gestiona rețetele

2024-08-21 06:30 UTC, en-marius-gociman commented on recipe-box-frontend/src/main/frontend/src/components/Footer/Footer.tsx
> +                ENDAVA</span>
Formatarea span-urilor putea fi mai ok, ceva în genul ăsta:

> <p>
                <span className="copy-symbol">
                    &copy;
                </span>
                &nbsp;
                {currentYear}
                &nbsp;
                <span className="bold-small">
                    ENDAVA
                </span>
</p>

`& nbsp;`

 este caracter pentru spațiu, asta ca să nu pierdem mult timp pe partea asta, avem și alte tickete :D

2024-08-21 12:07 UTC, en-marius-gociman approved these changes

2024-08-21 12:09 UTC, merged